apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespaces
  - gitea/namespace.yaml
  - prometheus/namespace.yaml
  - harbor/namespace.yaml

  # Cert-Manager Bootstrapping
  - cert-manager/cluster-issuer.yaml

  # Gitea Raw Config
  - gitea/ingressroute.yaml

  # Observability Raw Config
  - prometheus/ingressroute.yaml

  # Storage + Registry Raw Config
  - minio/tenant.yaml
  - minio/ingressroute.yaml
  - harbor/ingressroute.yaml
