# infra/rabbit-mq/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: apply-definitions-job
  namespace: rabbitmq
  annotations:
    argocd.argoproj.io/hook: PostSync

spec:
  backoffLimit: 5
  activeDeadlineSeconds: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: apply-definitions
          image: curlimages/curl:8.11.0
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ['ALL']
          env:
            - name: RABBITMQ_HOST
              value: 'rabbitmq.rabbitmq.svc.cluster.local'
            - name: RABBITMQ_PORT
              value: '15672'
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: rabbitmq-password
            - name: DEFINITIONS_PATH
              value: /definitions/definitions.json

          volumeMounts:
            - name: definitions
              mountPath: /definitions
              readOnly: true
          command:
            - /bin/sh
            - -ec
            - |
              echo "Applying RabbitMQ definitions from ${DEFINITIONS_PATH}..."

              curl -v --fail --show-error \
                --retry 30 \
                --retry-delay 5 \
                --retry-connrefused \
                -u "${RABBITMQ_USER}:${RABBITMQ_PASSWORD}" \
                -X POST \
                -H 'Content-Type: application/json' \
                --data-binary @"${DEFINITIONS_PATH}" \
                "http://${RABBITMQ_HOST}:${RABBITMQ_PORT}/api/definitions"

              echo "Successfully applied definitions."

      volumes:
        - name: definitions
          secret:
            secretName: rabbitmq-definitions
            defaultMode: 0444

