apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: rabbitmq
type: Opaque
stringData:
  rabbitmq-username: "admin_user"
  rabbitmq-password: "7140edb9e03b161bd324a6991b1247ef"
