apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-definitions
  namespace: rabbitmq
type: Opaque
stringData:
  definitions.json: |
    {
      "vhosts": [
        { "name": "/" }
      ],
      "exchanges": [
        {
          "vhost": "/",
          "name": "orders.exchange",
          "type": "topic",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        },
        {
          "vhost": "/",
          "name": "deadletter.exchange",
          "type": "direct",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        }
      ],
      "queues": [
        {
          "vhost": "/",
          "name": "orders.queue",
          "durable": true,
          "auto_delete": false,
          "arguments": {
            "x-dead-letter-exchange": "deadletter.exchange",
            "x-dead-letter-routing-key": "orders.dlq"
          }
        },
        {
          "vhost": "/",
          "name": "orders.dlq",
          "durable": true,
          "auto_delete": false,
          "arguments": {}
        }
      ],
      "bindings": [
        {
          "vhost": "/",
          "source": "orders.exchange",
          "destination": "orders.queue",
          "destination_type": "queue",
          "routing_key": "orders.*",
          "arguments": {},
          "properties_key": "orders.*"
        },
        {
          "vhost": "/",
          "source": "deadletter.exchange",
          "destination": "orders.dlq",
          "destination_type": "queue",
          "routing_key": "orders.dlq",
          "arguments": {},
          "properties_key": "orders.dlq"
        }
      ]
    }
