apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-apply-definitions
  namespace: rabbitmq
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 6
  activeDeadlineSeconds: 900
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq-apply-definitions
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: apply
          image: curlimages/curl:8.11.0
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ['ALL']
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq.rabbitmq.svc.cluster.local
            - name: RABBITMQ_PORT
              value: '15672'
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
            - name: DEFINITIONS_PATH
              value: /definitions/definitions.json
            - name: READY_MAX_ATTEMPTS
              value: '90'
            - name: READY_SLEEP_SECONDS
              value: '2'
            - name: APPLY_MAX_ATTEMPTS
              value: '10'
          volumeMounts:
            - name: definitions
              mountPath: /definitions
              readOnly: true
          command:
            - /bin/sh
            - -ec
            - |
              base_url="http://${RABBITMQ_HOST}:${RABBITMQ_PORT}"
              auth="${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}"
              log() { printf '%s %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }
              log "Waiting for RabbitMQ Management API..."
              i=1
              while [ "$i" -le "$READY_MAX_ATTEMPTS" ]; do
                code="$(curl -sS -u "$auth" -o /dev/null -w '%{http_code}' "$base_url/api/overview" || true)"
                [ "$code" = "200" ] && break
                sleep "$READY_SLEEP_SECONDS"
                i=$((i+1))
              done
              [ "$i" -gt "$READY_MAX_ATTEMPTS" ] && exit 1
              log "Applying definitions"
              attempt=1
              while [ "$attempt" -le "$APPLY_MAX_ATTEMPTS" ]; do
                code="$(curl -sS -u "$auth" -o /tmp/resp.txt -w '%{http_code}' -H 'Content-Type: application/json' --data-binary @"$DEFINITIONS_PATH" "$base_url/api/definitions" || true)"
                [ "$code" = "200" ] || [ "$code" = "201" ] || [ "$code" = "204" ] && exit 0
                sleep $((attempt*3))
                attempt=$((attempt+1))
              done
              exit 1
      volumes:
        - name: definitions
          secret:
            secretName: rabbitmq-definitions
