apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-definitions
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq-definitions
    app.kubernetes.io/instance: rabbitmq
type: Opaque
stringData:
  definitions.json: |
    {
      "vhosts": [
        { "name": "/" }
      ],
      "permissions": [
        {
          "user": "admin_user",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "exchanges": [
        {
          "vhost": "/",
          "name": "orders.exchange",
          "type": "topic",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        }
      ],
      "queues": [
        {
          "vhost": "/",
          "name": "orders.queue",
          "durable": true,
          "auto_delete": false,
          "arguments": {
            "x-dead-letter-exchange": "deadletter.exchange",
            "x-dead-letter-routing-key": "orders.dlq"
          }
        }
      ],
      "bindings": [
        {
          "vhost": "/",
          "source": "orders.exchange",
          "destination": "orders.queue",
          "destination_type": "queue",
          "routing_key": "orders.*",
          "arguments": {}
        }
      ]
    }
