apiVersion: v1
kind: Namespace
metadata:
  name: velero
  annotations:
    argocd.argoproj.io/sync-wave: '1'
---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: velero
#   namespace: velero
#   annotations:
#     argocd.argoproj.io/sync-wave: '2'
# ---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  labels:
    release: velero
spec:
  destination:
    name: in-cluster
    namespace: velero
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 8.1.0
    chart: velero
    helm:
      values: |-
        configuration:
          provider: hostPath
          backupStorageLocation:
            name: default
            config:
              path: /tmp/velero
          volumeSnapshotLocation:
            name: default
            config:
              path: /tmp/velero/snapshots
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
