apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Gitea Helm chart
    - chart: gitea
      repoURL: https://dl.gitea.com/charts/
      targetRevision: 10.6.0
      helm:
        valueFiles:
          - $values/infra/gitea/values/values.yaml
    # Values from Git (initially GitHub, migrated to Gitea in Phase 6)
    - repoURL: http://gitea-http.gitea.svc.cluster.local:3000/abdel/monitoring-logging-stack.git
      targetRevision: main
      ref: values
  destination:
    namespace: gitea
    name: in-cluster
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: 'true'
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
