apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  labels:
    release: kube-prometheus-stack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  sources:
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: kube-prometheus-stack
      targetRevision: 84.5.0
      helm:
        skipCrds: true
        releaseName: kps
        valueFiles:
          - $values/infra/prometheus/values/values.yaml
    - repoURL: http://gitea-http.gitea.svc.cluster.local:3000/abdel/monitoring-logging-stack.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true

